blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/Horuse/Splitwave/discussions
    about: Have a question, idea, or want to chat with the community? Start a discussion.
